# _____                _        ____ ___
#|_   _| __ __ ___   _(_)___   / ___|_ _|
#  | || '__/ _` \ \ / / / __| | |    | |
#  | || | | (_| |\ V /| \__ \ | |___ | |
#  |_||_|  \__,_| \_/ |_|___/  \____|___|
#

language: php

php:
 - 7.0

branches:
 - master

before_script:
 - curl -sL https://github.com/PocketMine/DevTools/releases/download/v1.11.0/DevTools_v1.11.0.phar -o DevTools.phar

script:
 - php build.php

notifications:
 email: false