name: Worlds
main: jjplaying\Worlds\Worlds
version: 1.0.5
api: 2.0.0
author: jjplaying
commands:
  worlds:
    description: "Worlds"
    usage: "/worlds <info|list> | /worlds <create|delete|load|unload|tp> <world> [type] | /worlds set <gamemode|build|pvp|damage|drop> <true|false>"
    aliases: ["ws"]
permissions:
  worlds.list:
    description: "List worlds"
    default: true
  worlds.admin:
    description: "Create worlds, delete worlds, set parameters"
    default: op
    children:
      worlds.admin.create:
        description: "Create and delete worlds"
        default: op
      worlds.admin.load:
        description: "Load and unload worlds"
        default: op
      worlds.admin.teleport:
        description: "Teleport to worlds"
        default: op
      worlds.admin.set:
        description: "Set parameters"
        default: op
      worlds.admin.build:
        description: "Allow building in protected worlds"
        default: op
      worlds.admin.gamemode:
        description: "Don't change gamemode to world's gamemode"
        default: false