name: Worlds
main: jjmc\Worlds\Worlds
version: 1.0.0
api: 1.0.0
author: jjmc
commands:
  worlds:
    description: "Worlds"
    usage: "/worlds <info|list|tp|set> [gamemode|build|pvp|damage|hunger|drop] [true|false]"
    aliases: ["ws"]
permissions:
  worlds.admin:
    description: "Create worlds, delete worlds, set parameters"
    default: op